### ISSUE TITLE
current status of the module

### ISSUE THREAD

**Issue by efstathiosntonas** [friyiajr/react-native-fast-lodash#3]
Hi @friyiajr, are you planning on resurrecting this module? Thanks

**Comment by friyiajr** [comment]
I have no plans to continue. In some cases its slower to cross the JSI bridge then it is to just stay in the JavaScript Runtime. Crossing the JSI slows down a lot of really basic methods making them worse then if you just ran them in JS. 

You only really get advantages from JSI when you run heavyweight processes on the Native Side and pass back results to the Runtime. If you are doing anything trivial, JSI is the worse option.

**Comment by efstathiosntonas** [comment]
Gotcha, thanks Daniel
